customhost = "employee.chcchcrqdo5m.us-east-1.rds.amazonaws.com"
customuser = "rakeshadmin"
custompass = "rakeshadmin"
customdb = "employee"
custombucket = "addemployeerakesh"
customregion = "us-east-1"
